### ISSUE TITLE
Create Application

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/poly-booking-api#1]
## Tasks
  - [x] Document initial design
  - [x] Create User Stories with tasks and acceptance criteria
  - [x] Create the the Heroku App and database
  - [x] Create the Django Project and add required modules
  - [x] Create  initial Database Entity diagram

**Comment by Polyanyanwu** [comment]
Completed
