### ISSUE TITLE
User Story: Maintain Facility and Room Type Codes

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/poly-booking-api#2]
As a **site owner** I can **maintain facility code and room types**,  so that **customers can have valid codes to use to describe hotel and rooms**

## Acceptance Criteria:
  - Menu item available to maintain facility code
  - Menu item available to maintain room tyles
  - Facility codes are added, deleted, updated successfully
  - Room type codes  are added, deleted, updated successfully
## Tasks
  - [x] Create static tables application
  - [x] Create models for facility and room types
  - [x] Create the url and update the menu
  - [x] Create the views to process the request
  - [x] Test the functionality

**Comment by Polyanyanwu** [comment]
Tables created as part of api application
