### ISSUE TITLE
User Story: Have an effective interface to login and logout

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/poly-booking-api#3]
As **site owner**, I can **have an effective interface to login and logout** so that **I can maintain data**

## Acceptance Criteria:
  - Sign-in link available on home page 
  - Sign-in page opens when link is clicked
  - Full user menu is available when successfully signed in

## Tasks
  - [x] Add sign-in link to home page
  - [x] Create sign-in page using Django Allauth
  - [x] Enable full user menu to signed in user

**Comment by Polyanyanwu** [comment]
Completed and tested
