### ISSUE TITLE
User Story: Access website on different devices (mobile first)

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/poly-booking-api#4]
As a **public user**, I want to be able to **access the website using different devices** so that **I will have same friendly experience.**

## Acceptance Criteria:
  - Website is accessible on different sized devices
  - Information is easy to find both on small and large screens 

## Tasks
  - [x] Use Bootstrap responsive design on all pages
  - [x] Ensure logo, title and menus appear on all pages consistently
  - [x] Test the functionality
