### ISSUE TITLE
User Story: Create Hotel Record

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/poly-booking-api#5]
As a **registered user**, I want to be able to **create hotel record via an API** so that **the hotel will be available for public view**

## Acceptance Criteria:
  - API endpoint is available for creating Hotel Record
  - Sending POST request to the API succeeds
  - Response is given to the user including hotel ID
  - The posted hotel is available for viewing

## Tasks
  - [x] Create the Model for the Hotel
  - [x] Create form to receive the request 
  - [x] Create view to process the request
  - [x] Test the functionality
