### ISSUE TITLE
User Story: Create/Update Hotel Rooms API

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/poly-booking-api#6]
As a **registered user**, I want to be able to **create/update/delete hotel room record via an API** so that **the rooms will be available for public view**

## Acceptance Criteria:
  - API endpoint is available for creating/updating Hotel Room Record
  - Sending POST request to the API succeeds
  - Sending PUT, DELETE request to the API succeeds
  - Response is given to the user including
  - The posted room is available for viewing

## Tasks
  - [x] Create the Model for the Hotel
  - [x] Create serializer to receive the request 
  - [x] Create view to process the request
  - [x] Test the functionality

**Comment by Polyanyanwu** [comment]
Completed and tested
