### ISSUE TITLE
User Story: View List of Hotels

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/poly-booking-api#7]
As a **public user**, I want to be able to **view list of hotels retrieved via an API on a friendly interface** so that **I can select a hotel for booking**

## Acceptance Criteria:
  - List of available hotels is visible at home page with summary details of the hotel

## Tasks
  - [x] Create the Model for the Hotel
  - [x] Create the template to display the hotels
  - [x] Create view to process the request
  - [x] Test the functionality

**Comment by Polyanyanwu** [comment]
Completed
