### ISSUE TITLE
User Story: View Details of a selected hotel

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/poly-booking-api#8]
As a **public user**, I want to be able to **view details of selected hotel retrieved via an API on a friendly interface** so that **I can see details of the hotel and rooms**

## Acceptance Criteria:
  - List of available hotels is visible at home page with summary details of the hotel
  - Clicking on a hotel will display the details of the hotel and rooms

## Tasks
  - [x] Create the template to display the hotel details
  - [x] Create view to process the request
  - [x] Test the functionality
